site_name: CMMS Api Doc
nav:
    - Account: index.md
    - Asset: './Asset/index.md'
    - AssetBusiness: './AssetBusiness/index.md'
    - AssetCategory: './AssetCategory/index.md'
    - AssetConsumingReference: './AssetConsumingReference/index.md'
    - AssetEvent: './AssetEvent/index.md'
    - AssetEventType: './AssetEventType/index.md'
    - AssetOfflineTracker: './AssetOfflineTracker/index.md'
    - AssetUser: './AssetUser/index.md'
    - BillingTerm: './BillingTerm/index.md'
    - Business: './Business/index.md'
    - BusinessGroup: './BusinessGroup/index.md'
    - CalendarEvent: './CalendarEvent/index.md'
    - ChargeDepartment: './ChargeDepartment/index.md'
    - File: './File/index.md'
    - FileContents: './FileContents/index.md'
    - MaintenanceType: './MaintenanceType/index.md'
    - MeterReading: './MeterReading/index.md'
    - MeterReadingUnit: './MeterReadingUnit/index.md'
    - Move: './Move/index.md'
    - MoveAsset: './MoveAsset/index.md'
    - MoveBack: './MoveBack/index.md'
    - MoveBackAsset: './MoveBackAsset/index.md'
    - MoveStatus: './MoveStatus/index.md'
    - Priority: './Priority/index.md'
    - Project: './Project/index.md'
    - PurchaseOrder: './PurchaseOrder/index.md'
    - PurchaseOrderLineItem: './PurchaseOrderLineItem/index.md'
    - PurchaseOrderStatus: './PurchaseOrderStatus/index.md'
    - ReasonToSetAssetOffline: './ReasonToSetAssetOffline/index.md'
    - ReasonToSetAssetOnline: './ReasonToSetAssetOnline/index.md'
    - Receipt: './Receipt/index.md'
    - ReceiptLineItem: './ReceiptLineItem/index.md'
    - ReceiptStatus: './ReceiptStatus/index.md'
    - ScheduledMaintenance: './ScheduledMaintenance/index.md'
    - ScheduledMaintenanceAsset: './ScheduledMaintenanceAsset/index.md'
    - ScheduledMaintenancePart: './ScheduledMaintenancePart/index.md'
    - ScheduleTrigger: './ScheduleTrigger/index.md'
    - User: './User/index.md'
    - WorkOrder: './WorkOrder/index.md'
    - WorkOrderAsset: './WorkOrderAsset/index.md'
    - WorkOrderBusiness: './WorkOrderBusiness/index.md'
    - WorkOrderPart: './WorkOrderPart/index.md'
    - WorkOrderStatus: './WorkOrderStatus/index.md'
    - WorkOrderStatusTransition: './WorkOrderStatusTransition/index.md'
    - WorkOrderTask: './WorkOrderTask/index.md'
    - WorkOrderUser: './WorkOrderUser/index.md'
    
    
theme: readthedocs
use_directory_urls: false